//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeDataEntities : DbContext
    {
        public EmployeeDataEntities()
            : base("name=EmployeeDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emp> Emps { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_UsersDetails> tbl_UsersDetails { get; set; }
    
        public virtual int insertdata(Nullable<int> emp_id, string first_name, string last_name)
        {
            var emp_idParameter = emp_id.HasValue ?
                new ObjectParameter("emp_id", emp_id) :
                new ObjectParameter("emp_id", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertdata", emp_idParameter, first_nameParameter, last_nameParameter);
        }
    
        public virtual int proc_registeration(string first_Name, string last_Name, string password, string email, Nullable<decimal> mobile_number, string current_address, Nullable<System.DateTime> dOB, Nullable<bool> gender, Nullable<int> country)
        {
            var first_NameParameter = first_Name != null ?
                new ObjectParameter("First_Name", first_Name) :
                new ObjectParameter("First_Name", typeof(string));
    
            var last_NameParameter = last_Name != null ?
                new ObjectParameter("Last_Name", last_Name) :
                new ObjectParameter("Last_Name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobile_numberParameter = mobile_number.HasValue ?
                new ObjectParameter("Mobile_number", mobile_number) :
                new ObjectParameter("Mobile_number", typeof(decimal));
    
            var current_addressParameter = current_address != null ?
                new ObjectParameter("Current_address", current_address) :
                new ObjectParameter("Current_address", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(bool));
    
            var countryParameter = country.HasValue ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_registeration", first_NameParameter, last_NameParameter, passwordParameter, emailParameter, mobile_numberParameter, current_addressParameter, dOBParameter, genderParameter, countryParameter);
        }
    
        public virtual int proc_registeration1(string first_Name, string last_Name, string password, string email, Nullable<decimal> mobile_number, string current_address, Nullable<System.DateTime> dOB, string gender, string country)
        {
            var first_NameParameter = first_Name != null ?
                new ObjectParameter("First_Name", first_Name) :
                new ObjectParameter("First_Name", typeof(string));
    
            var last_NameParameter = last_Name != null ?
                new ObjectParameter("Last_Name", last_Name) :
                new ObjectParameter("Last_Name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var mobile_numberParameter = mobile_number.HasValue ?
                new ObjectParameter("Mobile_number", mobile_number) :
                new ObjectParameter("Mobile_number", typeof(decimal));
    
            var current_addressParameter = current_address != null ?
                new ObjectParameter("Current_address", current_address) :
                new ObjectParameter("Current_address", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_registeration1", first_NameParameter, last_NameParameter, passwordParameter, emailParameter, mobile_numberParameter, current_addressParameter, dOBParameter, genderParameter, countryParameter);
        }
    }
}
