//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UsersDetails
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Id { get; set; }
        public decimal Mobile_number { get; set; }
        public string Current_address { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public byte[] Files { get; set; }
    }
}
